version: '3.8'

services:
  flask-dashboard:
    build: .
    command: python run_flask_dashboard.py
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=sqlite:///data/youth_justice.db
      - FLASK_ENV=development
      - LOG_LEVEL=DEBUG
    env_file:
      - .env
    restart: unless-stopped

  streamlit-dashboard:
    build: .
    command: python run_dashboard.py
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=sqlite:///data/youth_justice.db
      - LOG_LEVEL=INFO
    env_file:
      - .env
    restart: unless-stopped

  scheduler:
    build: .
    command: python run_automation.py
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=sqlite:///data/youth_justice.db
      - LOG_LEVEL=INFO
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - flask-dashboard

  # Optional: PostgreSQL for production
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=youth_justice
      - POSTGRES_USER=yjtracker
      - POSTGRES_PASSWORD=secure_password_here
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    profiles:
      - production

volumes:
  postgres_data: